// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqzfqrllvyrvsluwlfiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxemZxcmxsdnlydnNsdXdsZml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTIzOTMsImV4cCI6MjA3MTM4ODM5M30.WWO01JNoVExIvYhNx71P-kCGmuHK0w5Qb4fQIaLP5tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});